### ISSUE TITLE
Extraneous newlines in telnet server response

### ISSUE THREAD

**Issue by drguildo** [kolapapa/mini-telnet#3]
Thanks for writing and releasing this crate. I'm using it to collect diagnostic data from my router and seem to be getting extra newlines in the response from the telnet server.

When I telnet to my router using PuTTY and issue `xdslctl info` I get:

```
xdslctl: ADSL driver and PHY status
Status: Showtime
Last Retrain Reason:    1
Last initialization procedure status:   0
Max:    Upstream rate = 12578 Kbps, Downstream rate = 60380 Kbps
Bearer: 0, Upstream rate = 12835 Kbps, Downstream rate = 59803 Kbps
Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
```

but when I use mini-telnet and `let response = telnet.execute("xdslctl info").await?` and then `println!("{}", response)`, I get:

```
xdslctl: ADSL driver and PHY status

Status: Showtime

Last Retrain Reason:    1

Last initialization procedure status:   0

Max:    Upstream rate = 12578 Kbps, Downstream rate = 60276 Kbps

Bearer: 0, Upstream rate = 12835 Kbps, Downstream rate = 59803 Kbps

Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
```

Could it be https://github.com/kolapapa/mini-telnet/blob/250f39d6bbae9ab2dc0cbe3b89639a9574ac0697/src/lib.rs#L255 that's introducing the extra newlines?

**Comment by kolapapa** [comment]
It looks like this problem. I have fixed it in version `0.1.8`. Thank you again for your feedback~
